#!/bin/bash

BASENAME=docker-welt
CONTAINERS=containers

cd $(dirname $(readlink -f $0))
[ ! -e experiments ] && mkdir -v experiments

usage="$0 [option]

* Available templates
--------------------------
# In containers
$(ls containers)

# In experiments
$(ls experiments)
--------------------------

 -e:  Use experiemnts
 -C:  Use docker-compose

 -b:  [template] build 
 -r:  [template] run or up
 -d:  [template] down

 -u:  [username]


"

if [ $# -eq 0 ]; then
    echo "$usage"
    exit 0
fi

#--------------------------
# Functions
#--------------------------
build_docker(){
    local docker_image=$BASENAME/$template

    local container_dir=$CONTAINERS/$template
    [ ! -e $container_dir ] && echo "dir [$container_dir] does not exist" && exit -1

    ## Building an image
    local docker_command="docker build -t $docker_image ."
    [ "$USE_COMPOSER" == "ON" ] && docker_command="docker-compose build"

    ## Run
    cd $container_dir
    echo "$docker_command"
    eval $docker_command
}


run_docker(){
    local docker_image=$BASENAME/$template

    local container_dir=$CONTAINERS/$template
    [ ! -e $container_dir ] && echo "dir [$container_dir] does not exist" && exit -1


    local workarea="$PWD/workarea/$template"
    [ ! -e $workarea ] && mkdir -v $workarea

    ## Running an image
    case $USE_COMPOSER in
	ON)
	    docker_command="docker-compose up"
	    [ ! -e $container_dir/workarea ] && ln -s $workarea $container_dir/workarea
	    ;;
	*)
	    local xwin_option="-e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix"
	    [ -e $workarea/env.conf ] && local env_option="--env-file $workarea/env.conf"
	    [ ! -z "$docker_user" ] && local user_option="-u $docker_user"
	    local name=$template-$RANDOM
	    local sound_option="--device /dev/snd"
	    local docker_run_option="-h $name"
	    [ -e $container_dir/docker_run.conf ] && docker_run_option=$(cat $container_dir/docker_run.conf)
	    local docker_command="docker run -it --rm --name $name $docker_run_option $xwin_option $sound_option $env_option $user_option --volume=$workarea:/work $docker_image"
	    ;;
    esac

    ## Run
    cd $container_dir
    echo "$docker_command"
    eval $docker_command
}


down_docker(){
    local docker_image=$BASENAME/$template

    local container_dir=$CONTAINERS/$template
    [ ! -e $container_dir ] && echo "dir [$container_dir] does not exist" && exit -1

    docker_command="docker-compose down"

    ## Run
    cd $container_dir
    echo "$docker_command"
    eval $docker_command
}

#--------------------------
# Getopt
#--------------------------
while getopts "eCb:u:r:d:hv" op
  do
  case $op in
      e) CONTAINERS=experiments
	  ;;
      C) USE_COMPOSER=ON
	  ;;
      b) template="$OPTARG"
	  build_docker
	  ;;
      r) template="$OPTARG"
	  run_docker
	  ;;
      d) template="$OPTARG"
	  down_docker
	  ;;
      u) docker_user=$OPTARG
	  ;;
      h) echo "$usage"
	  exit 0
	  ;;
      v) echo "$version"
	  exit 0
	  ;;
      ?) echo "$usage"
	  exit 0
	  ;;
  esac
done



