# https://github.com/grafana/grafana/blob/master/Dockerfile
# https://hub.docker.com/r/grafana/grafana
FROM grafana/grafana:7.0.0


## Adding extra packages
#USER root


## Overwriting run script
ADD grafana-run.sh /run.sh

