version: "3.3"
services:

  # dCache head
  dcache:
    build:
     context: dcache/
     args:
       - DCACHE_MODE=head
    image: docker-welt/dcache
#    volumes:
#      - "$PWD/workarea/dcache_billing:/var/lib/dcache/billing"
    ports:
      - "2288:2288"
    networks:
      - dcache_net

  # dCache pool
  dcache_pool1:
    build:
      context: dcache/
      args:
       - DCACHE_MODE=pool
    image: docker-welt/dcache-pool
    networks:
      - dcache_net
    depends_on:
      - dcache



networks:
  dcache_net:
    driver: bridge
